# Stack name
name: o3s
# Apps deployed by stack
services:
  o3s:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_CHROME: ${INSTALL_CHROME:-false}
        INSTALL_CLAUDE: ${INSTALL_CLAUDE:-false}
        INSTALL_CODEX: ${INSTALL_CODEX:-false}
        INSTALL_LATEX: ${INSTALL_LATEX:-false}
        INSTALL_UV: ${INSTALL_UV:-false}
    image: o3s:latest
    container_name: o3s
    environment: # If tools are missing they are silently ignored
      - CODEX_HOME=/home/codespace/config/codex
      - CLAUDE_CONFIG_DIR=/home/codespace/config/claude
      - UV_PYTHON_INSTALL_DIR=/home/codespace/projects/.uv/python
      # Disable unneccesary claude network traffic
      - CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1
      - DISABLE_GROWTHBOOK=1
    env_file: .env
    volumes:
      # Host mount for dynamic changes
      - ../:/home/codespace/o3s
      # Configuration for tools
      - o3s-config:/home/codespace/config
      # Volume mount for project to work with across sessions
      - o3s-data:/home/codespace/projects
    # Limit ressource usage
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT}
          cpus: ${CPU_LIMIT}
        #reservations:
        #  devices:
        #    - driver: nvidia
        #      count: all
        #      capabilities: [gpu]
    # Required for iptables/ipset firewall management
    cap_add:
      - NET_ADMIN
      - NET_RAW
    # Keeps container runnning
    command: sleep infinity
    networks:
      - o3s

networks:
  o3s:
    name: o3s

volumes:
  o3s-config:
    name: o3s-config
  o3s-data:
    name: o3s-data
